### ISSUE TITLE
make a sound-speed slide rule

### ISSUE THREAD

**Issue by dankelley** [dankelley/sliderules#1]
I started fiddling with a while ago, and this issue is just to let others know.

**Comment by dankelley** [comment]
I did the other layers, so the four attached PDFs are the ones to print out for a trial.

There are assembly instructions at the top of each page, and the usage instructions are inside the top layer.

NOTE: I have not checked this for circle diameters, etc., but I think at least I have them in decreasing radius as you go "up" the layers.  (Otherwise it won't work!)

The principle is to write ss (sound speed) as

ss = f1(T) + f2(p) + f3(S)

where f1, f2 and f3 are functions determined by regressing a 20x20x20 array of values of T, p and S that cover an oceanic range.  Each layer maps its function into an angle around a circle. So, orienting the circles as in the instructions does the addition.

Of course, since I've not printed and tested it, al sorts of things can be wrong.  But it's only 3 sheets of paper, so not much loss.  A volunteer tester need not make a cursor ... a ruler will let you test values.  And there's no need to be super-careful in cutting the circles.  A push-pin would be a good a pivot, using a corkboard like the one outside my office.

**Comment by dankelley** [comment]
Oh, I see that I've messed up the axes. I want adjacent ones to have ticks pointing in opposite directions.  I'll need update it, and also to make a decision on good radii.

**Comment by dankelley** [comment]
I think it's working fairly well now.  To test (on a unix machine),
```
git pull
cd sound_speed
make clean
make
```
and you'll get five PDF files. The files
* `sound_speed_circular_1_bottom.pdf`
* `sound_speed_circular_1_middle.pdf`
* `sound_speed_circular_1_pointer.pdf`
* `sound_speed_circular_1_top.pdf`
are to be printed and then handled as in the assembly instructions given at top-left.  The file
* `sound_speed_circular_1_mockup.pdf`
shows what the resultant assembly ought to look like.  In this mockup I have not rotated the pointer to line up with S=30, but if you do that "by eye" and then read down to see the sound speed, you ought to understand how to use the slide rule.

<img width="812" alt="Screen Shot 2020-01-22 at 9 42 32 AM" src="https://user-images.githubusercontent.com/99469/72899389-49743880-3cfc-11ea-9309-0de99f8fefa0.png">

**Comment by manucook** [comment]
Thanks for doing this! I printed it out yesterday and the ticks for salinity were covered by the pressure scale but now that you've changed it, it looks great. 

Would it be possible to lengthen the pointer so that it covers more of the salinity scale. This is a minor detail but I think it would make it easier to line up the ticks.

**Comment by dankelley** [comment]
Good eye, @manucook!  I've updated the code to lengthen the pointer.  (A minor point: I also micro-positioned some letters, because my code for writing text along an angle is not doing kerning correctly.)

**Comment by dankelley** [comment]
Closing this because it's been done for nearly a year.
